[package]
name = "sysmon"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.25"
objc = "0.2.7"
sysinfo = "0.36"
once_cell = "1.19"
libc = "0.2"

[profile.release]
panic = "abort"
lto = true
strip = "symbols"
codegen-units = 1
overflow-checks = true